name: CI Tests

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: npm install --legacy-peer-deps
    - name: Build
      run: npm run ci-build
    - name: Check Code Style
      run: npm run lint
  
