name: CI Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Setup
        run: npm ci
      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v25
        with:
          config_path: 'eslint.config.mjs'
          extra_args: '--max-warnings=0'
      - name: Run Prettier on changed files
        # Always run both eslint and prettier
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          fail_on_error: true
          filter_mode: file
          level: warning
          prettier_flags: '**/*.{js,jsx,ts,tsx}'
          reporter: github-pr-check
      - name: Build
        run: npm run ci-build
